version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=recruitment
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${BACKEND_PORT:-5001}:5000"  # Changed default to 5001 to avoid conflicts
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/recruitment?authSource=admin
      - NODE_ENV=development
      - PORT=5000
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
